### ISSUE TITLE
wordsToNumbers('one two') // 3

### ISSUE THREAD

**Issue by jainanshul** [finnfiddle/words-to-numbers#2]
I was expecting it to return `12` but the answer I get is 3.

**Comment by finnfiddle** [comment]
At last I have some time to fix this but I would actually expect the words "one two" to resolve as `1` `2` instead of `12`. Maybe it would be a good idea to have an option for deciding what happens in this case where single digit numbers are placed consecutively in the input text. should they each resolve to separate numbers or instead one number composed of all the digits/numbers

**Comment by finnfiddle** [comment]
fixed. closing
